name: Build APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install -y git zip unzip openjdk-17-jdk
          pip3 install --user --upgrade buildozer Cython virtualenv
          echo 'export PATH=$PATH:~/.local/bin/' >> $GITHUB_ENV
      - name: Build with Buildozer
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          cd ${{ github.workspace }}
          buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
